// <auto-generated />
using System;
using DontGetSpicy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Web_API.Migrations
{
    [DbContext(typeof(DontGetSpicyContext))]
    [Migration("20210209113951_v8")]
    partial class v8
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DontGetSpicy.Models.Igra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<string>("accessCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("aleaIactaEst")
                        .HasColumnType("bit");

                    b.Property<int>("crveniIgracId")
                        .HasColumnType("int");

                    b.Property<string>("crveniUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("kreatorIgreID")
                        .HasColumnType("int");

                    b.Property<int>("naPotezu")
                        .HasColumnType("int");

                    b.Property<int>("plaviIgracId")
                        .HasColumnType("int");

                    b.Property<string>("plaviUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("stanjeIgre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StanjeIgre");

                    b.Property<int>("status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("zeleniIgracId")
                        .HasColumnType("int");

                    b.Property<string>("zeleniUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("zutiIgracId")
                        .HasColumnType("int");

                    b.Property<string>("zutiUsername")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("kreatorIgreID");

                    b.ToTable("Igra");
                });

            modelBuilder.Entity("DontGetSpicy.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("brojPobeda")
                        .HasColumnType("int")
                        .HasColumnName("BrojPobeda");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("slika")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Slika");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    b.HasKey("ID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("DontGetSpicy.Models.Potez", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("igraID")
                        .HasColumnType("int");

                    b.Property<int>("potezOdigrao")
                        .HasColumnType("int");

                    b.Property<int>("vrKocke")
                        .HasColumnType("int");

                    b.Property<DateTime>("vremeOdigravanja")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("igraID");

                    b.ToTable("Potezi");
                });

            modelBuilder.Entity("DontGetSpicy.Models.Igra", b =>
                {
                    b.HasOne("DontGetSpicy.Models.Korisnik", "kreatorIgre")
                        .WithMany("mojeIgre")
                        .HasForeignKey("kreatorIgreID");

                    b.Navigation("kreatorIgre");
                });

            modelBuilder.Entity("DontGetSpicy.Models.Potez", b =>
                {
                    b.HasOne("DontGetSpicy.Models.Igra", "igra")
                        .WithMany("potezi")
                        .HasForeignKey("igraID");

                    b.Navigation("igra");
                });

            modelBuilder.Entity("DontGetSpicy.Models.Igra", b =>
                {
                    b.Navigation("potezi");
                });

            modelBuilder.Entity("DontGetSpicy.Models.Korisnik", b =>
                {
                    b.Navigation("mojeIgre");
                });
#pragma warning restore 612, 618
        }
    }
}
