// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_API.Models;

namespace Web_API.Migrations
{
    [DbContext(typeof(DontGetSpicyContext))]
    [Migration("20210131172925_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Web_API.Models.Igra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int?>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("crveniIgracId")
                        .HasColumnType("int");

                    b.Property<int>("plaviIgracId")
                        .HasColumnType("int");

                    b.Property<string>("stanjeIgre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StanjeIgre");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.Property<int>("zeleniIgracId")
                        .HasColumnType("int");

                    b.Property<int>("zutiIgracId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("Igra");
                });

            modelBuilder.Entity("Web_API.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("brojPobeda")
                        .HasColumnType("int")
                        .HasColumnName("BrojPobeda");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("slika")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Slika");

                    b.HasKey("ID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("Web_API.Models.Igra", b =>
                {
                    b.HasOne("Web_API.Models.Korisnik", null)
                        .WithMany("mojeIgre")
                        .HasForeignKey("KorisnikID");
                });

            modelBuilder.Entity("Web_API.Models.Korisnik", b =>
                {
                    b.Navigation("mojeIgre");
                });
#pragma warning restore 612, 618
        }
    }
}
