// <auto-generated />
using System;
using DontGetSpicy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Web_API.Migrations
{
    [DbContext(typeof(DontGetSpicyContext))]
    partial class DontGetSpicyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DontGetSpicy.Models.Igra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("crveniIgracId")
                        .HasColumnType("int");

                    b.Property<int?>("kreatorIgreID")
                        .HasColumnType("int");

                    b.Property<int>("plaviIgracId")
                        .HasColumnType("int");

                    b.Property<string>("stanjeIgre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StanjeIgre");

                    b.Property<int>("status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("zeleniIgracId")
                        .HasColumnType("int");

                    b.Property<int>("zutiIgracId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("kreatorIgreID");

                    b.ToTable("Igra");
                });

            modelBuilder.Entity("DontGetSpicy.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("brojPobeda")
                        .HasColumnType("int")
                        .HasColumnName("BrojPobeda");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("slika")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Slika");

                    b.HasKey("ID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("DontGetSpicy.Models.Igra", b =>
                {
                    b.HasOne("DontGetSpicy.Models.Korisnik", "kreatorIgre")
                        .WithMany("mojeIgre")
                        .HasForeignKey("kreatorIgreID");

                    b.Navigation("kreatorIgre");
                });

            modelBuilder.Entity("DontGetSpicy.Models.Korisnik", b =>
                {
                    b.Navigation("mojeIgre");
                });
#pragma warning restore 612, 618
        }
    }
}
